version: '3.8'

services:
  
  battleship-postgres:
    container_name: battleship-postgres
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5436:5432"
    volumes:
      - battleship-postgres-volume:/var/lib/postgresql/data

volumes:
  battleship-postgres-volume: